---
tap_install:
  version:
    package_repo_bundle_tag: "1.6.1"
    package_version: "1.6.1"
  package_repository:
    oci_repository: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages
  values:
    profile: full
    shared:
      ingress_domain: tap-green.tanzu-google-lab.springapps.io
    ceip_policy_disclosed: true
    excluded_packages:
    - learningcenter.tanzu.vmware.com
    - workshops.learningcenter.tanzu.vmware.com
    - eventing.tanzu.vmware.com
