---
tap_install:
  version:
    package_repo_bundle_tag: "1.6.1"
    package_version: "1.6.1"
  package_repository:
    oci_repository: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages
  values:
    profile: full
    shared:
      ingress_domain: tap-green.tanzu-google-lab.springapps.io
    ceip_policy_disclosed: true
    excluded_packages:
    - learningcenter.tanzu.vmware.com
    - workshops.learningcenter.tanzu.vmware.com
    - eventing.tanzu.vmware.com
    namespace_provisioner:
      controller: false
      sync_period: 30s
      gitops_install:
        url: https://github.com/ccheetham/dotnet-dev-tap-gitops.git
        ref: origin/main
        subPath: clusters/dotnet-devx-tap-green/cluster-config/namespace-provisioner/namespaces
